packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  core-js: true
  esbuild: false
  msgpackr-extract: true
  netlify-cli: false
  prisma: true
  sharp: false
  unix-dgram: false
  workerd: true
